---
format: 
  revealjs:
    theme: scss/custom-dark.scss
    logo: images/FWS-logo.png
    footer: "[Alaska Data Week 2024](https://doimspp.sharepoint.com/sites/fws-FF07S00000-data/SitePages/Alaska-Data-Week-2024.aspx){.author}"
editor: source
highlight-style: tango
---

# A Reproducible Data Workflow {.smaller}

<br><br>

::: columns
::: {.column width="33%"}
[**McCrea Cobb**]{.author}

::: smaller
Refuge Inventory and Monitoring  
{{< fa envelope title="Email address logo" >}} [mccrea_cobb\@fws.gov](mailto:mccrea_cobb@fws.gov)  
{{< fa brands github title="The GitHub octocat logo" >}} [mccrea-cobb](https://github.com/mccrea-cobb)
:::
:::

::: {.column width="34%"}
[**Emma Schillerstrom**]{.author}

::: smaller
Refuge Inventory and Monitoring  
{{< fa envelope title="Email address logo" >}} [emma_shillerstrom\@fws.gov](mailto:emma_schillerstrom@fws.gov)  
{{< fa brands github title="The GitHub octocat logo" >}} [eschillerstrom-usfws](https://github.com/eschillerstrom-usfws)
:::
:::

::: {.column width="33%"}
[**Jonah Withers**]{.author}

::: smaller
Fisheries and Ecological Services  
{{< fa envelope title="Email address logo" >}} [jonah_withers\@fws.gov](mailto:jonah_withers@fws.gov)  
{{< fa brands github title="The GitHub octocat logo" >}} [JonahWithers-USFWS](https://github.com/JonahWithers-USFWS)
:::
:::
:::

<br><br>

::: {.center .smaller style="align-items: bottom;"}
{{< fa brands github title="The GitHub octocat logo" >}} <https://github.com/USFWS/data-workflow-presentation>
:::

::: notes

:::


## Potential Datasets {.smaller}

- [unmarked](https://github.com/hmecology/unmarked) R package (occupancy models, distance sampling)
    - [Canned data](https://github.com/hmecology/unmarked/tree/main/data)
    - [Simulated data analysis](https://hmecology.github.io/unmarked/articles/colext.html)
- 



## Visualize and summarize results

-   Self contained workflow

::: notes
-   Tons of options, R packages
-   Static versus dynamic visualizations
-   Depends on output file type (html vs. Word)
:::

```{r}
#| eval: true
#| echo: true

## Some code will go here
p <- 1+1
p
```


## Report results



::: notes
- R can output to many formats
- Mention the Alaska Refuge reporting series Quarto and Rmarkdown templates
:::


## Share products



::: notes
-   You can share your products through scripts
    -   Examples
        -   Emailing
        -   Publish report or app to server (Posit Connect)
        -   Save to data repository, share link
:::


## Preserve it all



::: notes
-   You can preserve your products using scripts
:::


## Demonstrate reuse



::: notes
-   You can replicate these steps if it is all scripted
-   Documentation is important!
:::


## Where to go from here



::: notes
-   NCTC trainings
-   Resources available
-   Who to reach out to
:::
